name: Run tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo
          coverage: none

      - name: Create database
        run: |
          sudo systemctl start mysql
          mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS testing;'

      - name: Install Composer dependencies
        run: composer install -n --prefer-dist

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Generate Passport keys
        run: php artisan passport:keys

      - name: Execute tests
        run: ./vendor/bin/phpunit
        env:
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: root
          MEDIA_DISK: local
